---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: 'Install a list of packages'
  apt:
    pkg:
    - htop
    - curl
    - python3-dev

- name: 'Creates workspace'
  file:
    path: /home/ubuntu/Workspace
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755
    
- name: 'Creates custom bin'
  file:
    path: /home/ubuntu/bin
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755    
    PATH=$PATH:~/bin

- name: 'Add a line to .profile'
  ansible.builtin.lineinfile:
    path: /home/ubuntu/bin
    line: PATH=$PATH:~/bin
    create: yes

- name: 'Git checkout jetson-fan-ctl'
  ansible.builtin.git:
    repo: 'https://gist.github.com/Pelirrojo/7128bf99635d5c87e10b58ade1bf74fe'
    dest: /home/ubuntu/bin
    version: HEAD

- name: 'Git checkout jetson-fan-ctl'
  ansible.builtin.git:
    repo: 'https://github.com/Pyrestone/jetson-fan-ctl'
    dest: /home/ubuntu/Workspace/jetson-fan-ctl
    version: HEAD

- name: 'Install jetson-fan-ctl'
  shell: cd /home/ubuntu/Workspace/jetson-fan-ctl && sudo ./install.sh
  async: 1
  poll: 0
  ignore_errors: true

- name: 'Install Jetson Stats'
  shell: sudo -H pip install -U jetson-stats
  async: 1
  poll: 0
  ignore_errors: true

- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
